name: new_wall
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  cached_network_image: ^3.2.0
  cloud_firestore: ^3.1.8
  cupertino_icons: ^1.0.2
  dio: ^4.0.4
  firebase_auth: ^3.3.5
  firebase_core: ^1.11.0
  firebase_storage: ^10.2.7
  flutter:
    sdk: flutter
  flutter_cache_manager: ^3.3.0
  flutter_riverpod: ^1.0.3
  flutter_staggered_grid_view: ^0.6.1
  flutter_wallpaper_manager: ^0.0.3
  gallery_saver: ^2.3.2
  google_fonts: ^2.3.2
  hive: ^2.0.6
  http: ^0.13.4
  json_annotation: ^4.4.0
  open_file: ^3.2.1
  path_provider: ^2.0.9
  permission_handler: ^9.2.0
  photo_view: ^0.13.0
  rename: ^2.0.1
  wallpaper: ^1.1.0

dev_dependencies:
  build_runner: ^2.1.7
  flutter_launcher_icons: ^0.9.2

  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.1.5

flutter:
  uses-material-design: true
