name: new_wall
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.19.6 <3.0.0"

dependencies:
  cached_network_image: ^3.2.3
  cloud_firestore: ^4.4.5
  cupertino_icons: ^1.0.5
  dio: ^4.0.4
  firebase_auth: ^4.3.0
  firebase_core: ^2.8.0
  firebase_storage: ^11.0.16
  flutter:
    sdk: flutter
  flutter_cache_manager: ^3.3.0
  flutter_local_notifications: ^12.0.4
  flutter_native_splash: ^2.2.16
  flutter_riverpod: ^2.3.2
  flutter_staggered_grid_view: ^0.6.2
  flutter_wallpaper_manager: ^0.0.3
  flutterfire_ui: ^0.4.1
  fluttertoast: ^8.2.1
  gallery_saver: ^2.3.2
  getwidget: ^2.0.5
  google_fonts: ^2.3.2
  hive: ^2.0.6
  http: ^0.13.4
  json_annotation: ^4.4.0
  open_file: ^3.2.1
i  path_provider: ^2.0.9
  permission_handler: ^10.2.0
  photo_view: ^0.14.0
  rename: ^2.0.1
  riverpod_annotation: ^2.0.2
  shimmer: ^2.0.0
  wallpaper: ^1.1.0

dev_dependencies:
  build_runner: ^2.1.7
  custom_lint: ^0.3.2
  flutter_launcher_icons: ^0.9.2

  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.1.5
  riverpod_generator: ^2.1.4
  riverpod_lint: ^1.1.6

flutter:
  uses-material-design: true
